name: pypi_upload

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: PyPI upload
    # master should be replaced by main (https://github.com/github/renaming#why-main)
    if: ${{ github.ref == 'refs/heads/master' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install latest pip, setuptools, twine + wheel
        run: |
          python -m pip install --upgrade pip setuptools twine wheel

      - name: Build wheels
        run: |
          python setup.py bdist_wheel
          python setup.py sdist

      - name: Upload to PyPI via Twine
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload --verbose -u '__token__' dist/*
